name: Dependency Submission (Dependabot)

on:
  push:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 21
          cache: 'gradle'

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4