name: Perform PoVerCat Release

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 23
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Build Sources
        run: ./gradlew build --no-daemon

      - name: Perform Release
        id: release
        run: ./gradlew release -Prelease.customUsername=${{ github.actor }} -Prelease.customPassword=${{ secrets.GITHUB_TOKEN }}

      - name: Publish Packages
        run: ./gradlew publish -Ppublish.username=${{ github.actor }} -Ppublish.token=${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Marker
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASED_VERSION: ${{ steps.release.outputs.released-version }}
        run: gh release create "v$RELEASED_VERSION" \
          --title="v$RELEASED_VERSION" \
          --generate-notes